# Generated by Django 4.0.1 on 2022-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='noimg.jpg', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
