# Generated by Django 4.1.2 on 2023-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rootLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
