# Generated by Django 4.2.4 on 2023-09-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consegna',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
