# Generated by Django 4.2.4 on 2023-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_consegna'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponibile',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
