# Generated by Django 4.2.4 on 2023-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_disponibile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idapi',
            field=models.CharField(db_index=True, default=None, max_length=200),
            preserve_default=False,
        ),
    ]
